#
# To generate the output file to partially incorporate to the README.md,
# execute this command in repository's folder: `terraform-docs -c .terraform-docs.yml .`.
#
# In case of using `pre-commit run -a` command, this file will be used automatically.
#

formatter: "markdown table"

version: ">= 0.13"

# header-from: main.tf
# footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 3
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
