#
# terraform-docs helps to generate an output file that will be partially incorporated into the README.md.
#
# Usage:
#   * cli: `terraform-docs -c .terraform-docs.yml .`.
#   * pre-commit: `pre-commit run -a`
#

formatter: "markdown table"

version: ">= 0.13"

recursive:
  enabled: true

sections:
  hide: []
  show: []

content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
